name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Pipeline running successfully ðŸš€"

      - name: Show date
        run: date

      - name: Show OS info
        run: uname -a

      - name: List files
        run: ls -la
